sudo: false
language: ruby
cache: 
  - bundler
  - directories:
    - "$HOME/.m2"
jdk:
  - oraclejdk8
rvm:
  - jruby-1.7.23
  - jruby-9.1.5.0
script:
- bundle exec rake vendor
- bundle exec rake install_jars
- bundle exec rspec spec
env:
- JRUBY_OPTS="--debug" CODECLIMATE_REPO_TOKEN=6a1c688e9dd3dced0a75faa22eab8a09b5a807a8e8023d0d38ce3738675d0f63 bundle exec rake
- JRUBY_OPTS="--debug" CODECLIMATE_REPO_TOKEN=6a1c688e9dd3dced0a75faa22eab8a09b5a807a8e8023d0d38ce3738675d0f63 bundle exec codeclimate-test-reporter
addons:
    code_climate:
        repo_token: 6a1c688e9dd3dced0a75faa22eab8a09b5a807a8e8023d0d38ce3738675d0f63
